# Generated by Django 3.0.6 on 2021-03-08 15:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TinTuc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='news_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
