# Generated by Django 3.0.6 on 2021-03-24 16:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TinTuc', '0009_auto_20210324_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='new_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
