# Generated by Django 3.0.6 on 2021-04-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TinTuc', '0010_auto_20210324_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blog_view',
            field=models.IntegerField(default=0),
        ),
    ]
